apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
  namespace: work
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    metadata:
      namespace: work  # Add this line  
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.cronjob.name }}
            image: {{ .Values.cronjob.image }}
            args:
              - /bin/sh
              - -c
              - echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure